# Generated by Django 5.2.17 on 2026-09-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('is_draft', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default="Khushaank Gupta's Weblog", max_length=120)),
                ('short_description', models.CharField(default='Notes, essays and useful things by Khushaank Gupta.', max_length=255)),
                ('author_name', models.CharField(default='Khushaank Gupta', max_length=120)),
                ('start_year', models.PositiveSmallIntegerField(default=2026)),
                ('base_url', models.URLField(default='http://localhost:8000')),
                ('default_seo_description', models.TextField(blank=True)),
                ('default_social_image', models.ImageField(blank=True, upload_to='site/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('newsletter_url', models.URLField(blank=True)),
                ('footer_disclosure', models.TextField(blank=True)),
                ('colophon', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='SponsorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('color_scheme', models.CharField(default='blue', max_length=20)),
            ],
        ),
    ]
