# Generated by Django 5.2.17 on 2026-09-22 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('quotation', models.TextField()),
                ('source', models.CharField(max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('commentary', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ('-published_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='notes/%Y/%m/')),
                ('video_url', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ('-published_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=180)),
                ('url', models.URLField()),
                ('commentary', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='links/%Y/%m/')),
                ('slug', models.SlugField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ('-published_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Elsewhere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('url', models.URLField()),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('podcast', 'Podcast'), ('interview', 'Interview'), ('article', 'Article'), ('video', 'Video'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='GuideChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='blog.guide')),
            ],
            options={
                'ordering': ('number',),
                'constraints': [models.UniqueConstraint(fields=('guide', 'slug'), name='unique_chapter_slug_per_guide')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('hero_image', models.ImageField(blank=True, upload_to='entries/%Y/%m/')),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='blog.series')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ('-published_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['is_draft', 'published_at'], name='blog_entry_is_draf_48d4c2_idx'), models.Index(fields=['is_featured', 'published_at'], name='blog_entry_is_feat_b50097_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'published_at'), name='unique_entry_slug_date')],
            },
        ),
    ]
