# Generated by Django 5.2.17 on 2026-09-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-published_at',)},
        ),
    ]
