# Generated by Django 5.2.17 on 2026-09-22 10:56

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', validators=[media_library.models.validate_media_file])),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=8)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, upload_to='uploads/posters/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
